"""
Nova AI — PDF Report Generator (ReportLab)
Produces a professional consultant-grade PDF report.
"""
import os
import math
from datetime import datetime
from pathlib import Path

from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.units import mm, cm
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.enums import TA_CENTER, TA_LEFT, TA_JUSTIFY
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle,
    HRFlowable, PageBreak, KeepTogether
)
from reportlab.graphics.shapes import Drawing, Wedge, String, Circle, Rect
from reportlab.graphics import renderPDF
from reportlab.graphics.charts.spider import SpiderChart

from app.config import get_settings

settings = get_settings()

# ── Brand Colors ───────────────────────────────────────────────────────────────
PRIMARY = colors.HexColor("#6366F1")       # Indigo
SECONDARY = colors.HexColor("#8B5CF6")     # Purple
ACCENT = colors.HexColor("#10B981")        # Emerald
DANGER = colors.HexColor("#EF4444")        # Red
WARNING = colors.HexColor("#F59E0B")       # Amber
DARK = colors.HexColor("#0F172A")          # Slate 900
LIGHT_BG = colors.HexColor("#F8FAFC")      # Slate 50
MID_GRAY = colors.HexColor("#64748B")      # Slate 500
BORDER = colors.HexColor("#E2E8F0")        # Slate 200

W, H = A4


def _grade_color(grade: str) -> colors.Color:
    if grade in ("A+", "A"): return ACCENT
    if grade in ("B+", "B"): return colors.HexColor("#3B82F6")
    if grade in ("C+", "C"): return WARNING
    return DANGER


def _score_color(score: float) -> colors.Color:
    if score >= 80: return ACCENT
    if score >= 60: return colors.HexColor("#3B82F6")
    if score >= 40: return WARNING
    return DANGER


def _make_styles():
    styles = getSampleStyleSheet()
    base = styles["Normal"]
    return {
        "title": ParagraphStyle("Title", parent=base, fontSize=28, textColor=colors.white,
                                 fontName="Helvetica-Bold", alignment=TA_CENTER, spaceAfter=6),
        "subtitle": ParagraphStyle("Subtitle", parent=base, fontSize=13, textColor=colors.HexColor("#CBD5E1"),
                                    fontName="Helvetica", alignment=TA_CENTER, spaceAfter=4),
        "h1": ParagraphStyle("H1", parent=base, fontSize=18, textColor=DARK,
                               fontName="Helvetica-Bold", spaceBefore=16, spaceAfter=8),
        "h2": ParagraphStyle("H2", parent=base, fontSize=13, textColor=PRIMARY,
                               fontName="Helvetica-Bold", spaceBefore=12, spaceAfter=6),
        "body": ParagraphStyle("Body", parent=base, fontSize=9.5, textColor=MID_GRAY,
                                fontName="Helvetica", leading=15, alignment=TA_JUSTIFY),
        "bullet": ParagraphStyle("Bullet", parent=base, fontSize=9, textColor=DARK,
                                  fontName="Helvetica", leftIndent=12, spaceAfter=3),
        "caption": ParagraphStyle("Caption", parent=base, fontSize=8, textColor=MID_GRAY,
                                   fontName="Helvetica-Oblique", alignment=TA_CENTER),
        "score_big": ParagraphStyle("ScoreBig", parent=base, fontSize=52, textColor=PRIMARY,
                                     fontName="Helvetica-Bold", alignment=TA_CENTER),
        "grade_big": ParagraphStyle("GradeBig", parent=base, fontSize=22, textColor=SECONDARY,
                                     fontName="Helvetica-Bold", alignment=TA_CENTER),
    }


def _header_footer(canvas, doc):
    canvas.saveState()
    # Header bar
    canvas.setFillColor(PRIMARY)
    canvas.rect(0, H - 18 * mm, W, 18 * mm, fill=1, stroke=0)
    canvas.setFont("Helvetica-Bold", 9)
    canvas.setFillColor(colors.white)
    canvas.drawString(15 * mm, H - 11 * mm, "NOVA AI  |  Marketing Intelligence Report")
    canvas.drawRightString(W - 15 * mm, H - 11 * mm, datetime.now().strftime("%B %d, %Y"))
    # Footer
    canvas.setFillColor(BORDER)
    canvas.rect(0, 0, W, 10 * mm, fill=1, stroke=0)
    canvas.setFont("Helvetica", 8)
    canvas.setFillColor(MID_GRAY)
    canvas.drawString(15 * mm, 3.5 * mm, "Confidential — Generated by Nova AI")
    canvas.drawRightString(W - 15 * mm, 3.5 * mm, f"Page {doc.page}")
    canvas.restoreState()


def _cover_page(styles, result: dict) -> list:
    elements = []
    score = result.get("overall_score", 0)
    grade = result.get("grade", "N/A")
    url = result.get("url", "")

    # Cover drawing
    d = Drawing(W - 40 * mm, 80 * mm)
    d.add(Rect(0, 0, W - 40 * mm, 80 * mm, fillColor=DARK, strokeColor=None))
    d.add(String((W - 40 * mm) / 2, 52 * mm, "MARKETING AUDIT REPORT",
                  fontSize=14, fillColor=colors.HexColor("#CBD5E1"),
                  fontName="Helvetica-Bold", textAnchor="middle"))
    d.add(String((W - 40 * mm) / 2, 35 * mm, f"{score:.0f}",
                  fontSize=56, fillColor=_score_color(score),
                  fontName="Helvetica-Bold", textAnchor="middle"))
    d.add(String((W - 40 * mm) / 2, 22 * mm, f"Overall Score  ·  Grade: {grade}",
                  fontSize=12, fillColor=colors.HexColor("#94A3B8"),
                  fontName="Helvetica", textAnchor="middle"))
    d.add(String((W - 40 * mm) / 2, 10 * mm, url[:80],
                  fontSize=9, fillColor=colors.HexColor("#64748B"),
                  fontName="Helvetica-Oblique", textAnchor="middle"))
    elements.append(Spacer(1, 20 * mm))
    elements.append(d)
    elements.append(Spacer(1, 8 * mm))
    elements.append(Paragraph(f"<b>Analyzed:</b> {datetime.now().strftime('%B %d, %Y at %H:%M')}", styles["caption"]))
    elements.append(Paragraph(f"Business Type: {result.get('business_type', 'N/A').title()}", styles["caption"]))
    elements.append(PageBreak())
    return elements


def _score_table(styles, modules: dict) -> list:
    elements = [Paragraph("Module Scores", styles["h1"])]
    AGENT_LABELS = {
        "content": "Content & Messaging",
        "strategy": "Business Strategy",
        "conversion": "Conversion Optimization",
        "technical": "Technical SEO",
        "webvitals": "Web Vitals & Performance",
        "competitive": "Competitive Intelligence",
        "accessibility": "Accessibility (WCAG)",
        "security": "Security & Trust",
    }
    data = [["Module", "Score", "Grade", "Weight", "Status"]]
    for mod, info in modules.items():
        score = info.get("score", 0)
        grade = info.get("grade", "N/A")
        weight = info.get("weight", 0)
        status = "⚠ Failed" if info.get("error") else ("✓ Pass" if score >= 60 else "✗ Fail")
        data.append([
            AGENT_LABELS.get(mod, mod.title()),
            f"{score:.0f}/100",
            grade,
            f"{weight*100:.0f}%",
            status,
        ])

    ts = TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), PRIMARY),
        ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
        ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
        ("FONTSIZE", (0, 0), (-1, -1), 9),
        ("ROWBACKGROUNDS", (0, 1), (-1, -1), [LIGHT_BG, colors.white]),
        ("GRID", (0, 0), (-1, -1), 0.3, BORDER),
        ("ALIGN", (1, 0), (-1, -1), "CENTER"),
        ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
        ("LEFTPADDING", (0, 0), (-1, -1), 8),
        ("RIGHTPADDING", (0, 0), (-1, -1), 8),
        ("TOPPADDING", (0, 0), (-1, -1), 6),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
    ])
    col_widths = [90 * mm, 25 * mm, 20 * mm, 20 * mm, 25 * mm]
    t = Table(data, colWidths=col_widths, repeatRows=1)
    t.setStyle(ts)
    elements.append(t)
    elements.append(Spacer(1, 6 * mm))
    return elements


def _narrative_section(styles, narrative: str) -> list:
    elements = [Paragraph("Executive Summary", styles["h1"])]
    for para in narrative.split("\n\n"):
        if para.strip():
            elements.append(Paragraph(para.strip(), styles["body"]))
            elements.append(Spacer(1, 4 * mm))
    return elements


def _findings_section(styles, findings: list, quick_wins: list) -> list:
    elements = [Paragraph("Key Findings & Quick Wins", styles["h1"])]
    elements.append(Paragraph("Critical Issues Found", styles["h2"]))
    for f in findings[:12]:
        text = f.get("text", f) if isinstance(f, dict) else f
        agent = f.get("agent", "") if isinstance(f, dict) else ""
        tag = f" <font color='#6366F1'>[{agent.upper()}]</font>" if agent else ""
        elements.append(Paragraph(f"• {text}{tag}", styles["bullet"]))
    elements.append(Spacer(1, 4 * mm))
    elements.append(Paragraph("Quick Wins (Implement This Week)", styles["h2"]))
    for w in quick_wins[:8]:
        elements.append(Paragraph(f"✓ {w}", styles["bullet"]))
    return elements


def _module_detail_section(styles, modules: dict) -> list:
    elements = [PageBreak(), Paragraph("Detailed Module Analysis", styles["h1"])]
    LABELS = {
        "content": "Content & Messaging",
        "strategy": "Business Strategy",
        "conversion": "Conversion Optimization",
        "technical": "Technical SEO",
        "webvitals": "Web Vitals",
        "competitive": "Competitive Intelligence",
        "accessibility": "Accessibility",
        "security": "Security & Trust",
    }
    for mod, info in modules.items():
        score = info.get("score", 0)
        grade = info.get("grade", "N/A")
        label = LABELS.get(mod, mod.title())
        block = [
            Paragraph(f"{label}  —  {score:.0f}/100  ({grade})", styles["h2"]),
            Paragraph(info.get("score_justification", ""), styles["body"]),
            Spacer(1, 3 * mm),
        ]
        for strength in info.get("strengths", [])[:3]:
            block.append(Paragraph(f"<font color='#10B981'>✓</font> {strength}", styles["bullet"]))
        for finding in info.get("findings", [])[:4]:
            block.append(Paragraph(f"<font color='#EF4444'>✗</font> {finding}", styles["bullet"]))
        block.append(Spacer(1, 5 * mm))
        elements.append(KeepTogether(block))
    return elements


async def generate_pdf_report(result: dict, audit_id: str) -> str:
    """Generate PDF and return the file path."""
    reports_dir = Path(settings.reports_dir)
    reports_dir.mkdir(parents=True, exist_ok=True)
    filepath = reports_dir / f"nova_audit_{audit_id}.pdf"

    styles = _make_styles()
    doc = SimpleDocTemplate(
        str(filepath),
        pagesize=A4,
        leftMargin=20 * mm,
        rightMargin=20 * mm,
        topMargin=25 * mm,
        bottomMargin=18 * mm,
    )

    story = []
    story += _cover_page(styles, result)
    story += _narrative_section(styles, result.get("executive_narrative", "No narrative generated."))
    story.append(Spacer(1, 6 * mm))
    story += _score_table(styles, result.get("modules", {}))
    story.append(PageBreak())
    story += _findings_section(styles, result.get("findings", []), result.get("quick_wins", []))
    story += _module_detail_section(styles, result.get("modules", {}))

    doc.build(story, onFirstPage=_header_footer, onLaterPages=_header_footer)
    return str(filepath)
